sonata_admin:
    title: 'Sonata Admin'
    templates:
        layout: '@SonataTranslation/standard_layout.html.twig'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
    show_mosaic_button:   false

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
